language: node_js
node_js:
  - 16
sudo: required
services:
  - docker

before_install:
## Build
  - docker build -t udagram-api-feed ./Projects/Lession3/udagram-api-feed
  - docker build  -t udagram-api-user ./Projects/Lession3/udagram-api-user
  - docker build  -t udagram-frontend ./Projects/Lession3/udagram-frontend
  - docker build  -t udagram-reverseproxy ./Projects/Lession3/udagram-reverseproxy
## Tagging
  - docker tag udagram-api-feed daominhtoan09/udagram-api-feed:v1
  - docker tag udagram-api-user daominhtoan09/udagram-api-user:v1
  - docker tag udagram-frontend daominhtoan09/udagram-frontend:v1
  - docker tag udagram-reverseproxy daominhtoan09/udagram-reverseproxy:v1
## Do similar for other three images```
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push daominhtoan09/udagram-api-feed:v1
  - docker push daominhtoan09/udagram-api-user:v1
  - docker push daominhtoan09/udagram-frontend:v1
  - docker push daominhtoan09/udagram-reverseproxy:v1
## Do similar for other three images
## test