apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    run: udagram-reverseproxy
spec:
  selector:
    app: udagram-reverseproxy
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
