version: "3"
services:
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
    extra_hosts: 
      - host.docker.internal:host-gateway
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
    extra_hosts: 
      - host.docker.internal:host-gateway
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
    depends_on:
      - backend_user
      - backend_feed
  