apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env-value
data:
  POSTGRES_DB: postgres
  POSTGRES_HOST: database-1.chjzyzuqbxdd.us-east-1.rds.amazonaws.com
  POSTGRES_DIALECT: postgres
  AWS_REGION: us-east-1
  AWS_PROFILE: prod
  AWS_BUCKET: toandm9-bucket
  URL: localhost:8080
  JWT_SECRET: dG9hbmRtOWFhc2xqZmxzZGpsc2psZmpzZGxrZmpqYWxrZHNmamxrYXNkamZsa3NkYQ==
  # the data is abbreviated in this example