apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: daominhtoan09/udagram-frontend:v1
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: config-env-value
          - secretRef:
              name: secret-env-value
